# Default configuration
discord:
  url: "https://discord.com/api/v9/interactions"
  mj:
    id: "936929561302675456"
    session: "2fb980f65e5c9a77c96ca01f2c242cf6"
    imagine:
      id: "938956540159881230"
      name: "imagine"
      version: "1077969938624553050"
      description: "Create images with Midjourney"